### ISSUE TITLE
Only one callback gets called

### ISSUE THREAD

**Issue by sentialx** [getstation/electron-better-web-request#11]
It appears that when for example using multiple `onBeforeRequest` events, only the last one gets executed.

```typescript
webRequest.onBeforeRequest(
    { urls: ['<all_urls>'] },
    async (details: Electron.OnBeforeRequestDetails, callback: any) => {
      console.log('test1');
      callback({ cancel: false });
    },
);

webRequest.onBeforeRequest(
    { urls: ['<all_urls>'] },
    async (details: Electron.OnBeforeRequestDetails, callback: any) => {
      console.log('test2');
      callback({ cancel: false });
    },
);
```

Prints: test2

**Comment by hugomano** [comment]
@sentialx, you need to define your strategy with `setResolver` (see the sample in the [usage section](https://github.com/getstation/electron-better-web-request#usage)). The default resolver modifies the web request only with the last registered listener like in Electron.
